apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  outbound:
    serviceReferences:
    - name: choreo:///apifirst/testprojecthanis/hellow2/803f0/v1/PUBLIC
      connectionConfig: 01f00556-76fb-16a8-90f1-bfdebbce3e5c
      env:
      - from: ServiceURL
        to: API_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
