apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  outbound:
    serviceReferences:
    - name: choreo:///apifirst/testeu/greeting-service-bal/8b1c3/v1/PUBLIC
      connectionConfig: 01f0055b-541f-1850-a5a7-59f91c297672
      env:
      - from: ServiceURL
        to: API_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
