apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  outbound:
    serviceReferences:
    - name: choreo:///apifirst/testeu/greeting-service-bal/8b1c3/v1/PUBLIC
      connectionConfig: 01f00560-f7bf-1640-82a6-93f6f5b69a3e
      env:
      - from: ServiceURL
        to: API_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
