apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  outbound:
    serviceReferences:
    - name: choreo:///hansijk/iasf/publishercomponent1/8b1c3/v1/PUBLIC
      connectionConfig: 01ef9bfe-1e0d-1e46-8fc3-bc7df5bf1d80
      env:
      - from: ServiceURL
        to: API_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
